window.portfolioItems = [
  {
    title: "官网-AI 产品",
    category: "ui",
    categoryLabel: "UI",
    subtype: "官网Banner",
    src: "./assets/portfolio/01-ui.jpg",
    original: "UI设计/网页设计/官网/官网-AI 产品.png",
  },
  {
    title: "官网-智慧园区",
    category: "ui",
    categoryLabel: "UI",
    subtype: "官网Banner",
    src: "./assets/portfolio/02-ui.jpg",
    original: "UI设计/网页设计/官网/官网-智慧园区.png",
  },
  {
    title: "官网-智慧国资",
    category: "ui",
    categoryLabel: "UI",
    subtype: "官网Banner",
    src: "./assets/portfolio/03-ui.jpg",
    original: "UI设计/网页设计/官网/官网-智慧国资.png",
  },
  {
    title: "官网-智慧物业",
    category: "ui",
    categoryLabel: "UI",
    subtype: "官网Banner",
    src: "./assets/portfolio/04-ui.jpg",
    original: "UI设计/网页设计/官网/官网-智慧物业.png",
  },
  {
    title: "page-1-关于我们",
    category: "ui",
    categoryLabel: "UI",
    subtype: "官网页面",
    src: "./assets/portfolio/05-ui.jpg",
    original: "UI设计/网页设计/官网/page-1-关于我们.png",
  },
  {
    title: "变更",
    category: "ui",
    categoryLabel: "UI",
    subtype: "产品页面",
    src: "./assets/portfolio/06-ui.jpg",
    original: "UI设计/网页设计/变更.png",
  },
  {
    title: "经典蓝",
    category: "ui",
    categoryLabel: "UI",
    subtype: "产品页面",
    src: "./assets/portfolio/07-ui.jpg",
    original: "UI设计/网页设计/经典蓝.png",
  },
  {
    title: "续签合同",
    category: "ui",
    categoryLabel: "UI",
    subtype: "产品页面",
    src: "./assets/portfolio/08-ui.jpg",
    original: "UI设计/网页设计/续签合同.png",
  },
  {
    title: "回款分析1",
    category: "ui",
    categoryLabel: "UI",
    subtype: "看板",
    src: "./assets/portfolio/09-ui.jpg",
    original: "UI设计/网页设计/看板/回款分析1.png",
  },
  {
    title: "金华看板",
    category: "ui",
    categoryLabel: "UI",
    subtype: "看板",
    src: "./assets/portfolio/10-ui.jpg",
    original: "UI设计/网页设计/看板/金华看板_画板 1 副本 3.png",
  },
  {
    title: "7周年",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "banner",
    src: "./assets/portfolio/11-graphic.jpg",
    original: "平面/banner/7周年.png",
  },
  {
    title: "ai 演讲大赛",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "banner",
    src: "./assets/portfolio/12-graphic.jpg",
    original: "平面/banner/ai 演讲大赛.png",
  },
  {
    title: "cosmic",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "banner",
    src: "./assets/portfolio/13-graphic.jpg",
    original: "平面/banner/cosmic.png",
  },
  {
    title: "主kv2",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "banner",
    src: "./assets/portfolio/14-graphic.jpg",
    original: "平面/banner/主kv2.png",
  },
  {
    title: "公众号banner",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "banner",
    src: "./assets/portfolio/15-graphic.jpg",
    original: "平面/banner/公众号banner.png",
  },
  {
    title: "台历展示",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "印刷",
    src: "./assets/portfolio/16-graphic.jpg",
    original: "平面/印刷/台历展示.jpg",
  },
  {
    title: "台历展示",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "印刷",
    src: "./assets/portfolio/17-graphic.jpg",
    original: "平面/印刷/台历展示.png",
  },
  {
    title: "物业折页（转曲）",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "印刷",
    src: "./assets/portfolio/18-graphic.jpg",
    original: "平面/印刷/物业折页（转曲）_画板 1 副本 2.png",
  },
  {
    title: "物业折页（转曲）",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "印刷",
    src: "./assets/portfolio/19-graphic.jpg",
    original: "平面/印刷/物业折页（转曲）_画板 1 副本 3.png",
  },
  {
    title: "创见者电子版",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "展会",
    src: "./assets/portfolio/20-graphic.jpg",
    original: "平面/展会/创见者电子版.png",
  },
  {
    title: "北京展会2",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "展会",
    src: "./assets/portfolio/21-graphic.jpg",
    original: "平面/展会/北京展会2.png",
  },
  {
    title: "协会活动kv",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "展会",
    src: "./assets/portfolio/22-graphic.jpg",
    original: "平面/展会/协会活动kv.jpg",
  },
  {
    title: "周年庆活动kv设计",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "展会",
    src: "./assets/portfolio/23-graphic.jpg",
    original: "平面/展会/周年庆活动kv设计.jpg",
  },
  {
    title: "深圳物博会邀请函",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "展会",
    src: "./assets/portfolio/24-graphic.jpg",
    original: "平面/展会/深圳物博会邀请函.png",
  },
  {
    title: "物博会展台设计",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "展会",
    src: "./assets/portfolio/25-graphic.jpg",
    original: "平面/展会/物博会展台设计.JPG",
  },
  {
    title: "物博会线下展会kv设计",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "展会",
    src: "./assets/portfolio/26-graphic.jpg",
    original: "平面/展会/物博会线下展会kv设计.jpg",
  },
  {
    title: "论坛活动kv设计",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "展会",
    src: "./assets/portfolio/27-graphic.jpg",
    original: "平面/展会/论坛活动kv设计.jpg",
  },
  {
    title: "邀请函",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "展会",
    src: "./assets/portfolio/28-graphic.jpg",
    original: "平面/展会/邀请函.png",
  },
  {
    title: "创业公社",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "运营",
    src: "./assets/portfolio/29-graphic.jpg",
    original: "平面/运营/创业公社.png",
  },
  {
    title: "培训10.22毛卫",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "运营",
    src: "./assets/portfolio/30-graphic.jpg",
    original: "平面/运营/培训10.22毛卫.png",
  },
  {
    title: "培训海报",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "运营",
    src: "./assets/portfolio/31-graphic.jpg",
    original: "平面/运营/培训海报.png",
  },
  {
    title: "支付宝活动",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "运营",
    src: "./assets/portfolio/32-graphic.jpg",
    original: "平面/运营/支付宝活动.png",
  },
  {
    title: "收款码",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "运营",
    src: "./assets/portfolio/33-graphic.jpg",
    original: "平面/运营/收款码.png",
  },
  {
    title: "旗舰版",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "运营",
    src: "./assets/portfolio/34-graphic.jpg",
    original: "平面/运营/旗舰版.png",
  },
  {
    title: "pos",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "长图页面",
    src: "./assets/portfolio/35-graphic.jpg",
    original: "平面/长图页面/pos.png",
  },
  {
    title: "国资解决方案长图",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "长图页面",
    src: "./assets/portfolio/36-graphic.jpg",
    original: "平面/长图页面/国资解决方案长图.png",
  },
  {
    title: "支付宝海报",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "长图页面",
    src: "./assets/portfolio/37-graphic.jpg",
    original: "平面/长图页面/支付宝海报.png",
  },
  {
    title: "智慧园区解决方案长图",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "长图页面",
    src: "./assets/portfolio/38-graphic.jpg",
    original: "平面/长图页面/智慧园区解决方案长图_画板 1.jpg",
  },
  {
    title: "灵析智报-长图2",
    category: "graphic",
    categoryLabel: "平面",
    subtype: "长图页面",
    src: "./assets/portfolio/39-graphic.jpg",
    original: "平面/长图页面/灵析智报-长图2.png",
  },
  {
    title: "封面",
    category: "video",
    categoryLabel: "短视频",
    subtype: "短视频",
    src: "./assets/portfolio/40-video.jpg",
    original: "短视频/封面.png",
  },
  {
    title: "灵析智报01封面",
    category: "video",
    categoryLabel: "短视频",
    subtype: "短视频",
    src: "./assets/portfolio/41-video.jpg",
    original: "短视频/灵析智报01封面.png",
  },
  {
    title: "灵析智报02封面",
    category: "video",
    categoryLabel: "短视频",
    subtype: "短视频",
    src: "./assets/portfolio/42-video.jpg",
    original: "短视频/灵析智报02封面.png",
  },
  {
    title: "灵析智报产品发布封面",
    category: "video",
    categoryLabel: "短视频",
    subtype: "短视频",
    src: "./assets/portfolio/43-video.jpg",
    original: "短视频/灵析智报产品发布封面.png",
  },
];
window.portfolioCounts = { ui: 10, graphic: 29, video: 4 };
